pennchatsproject/core/views.py
# pennchatsproject/core/views.py
# includes routing code for two views (homepage view and the about us view)
# Audra's main.py line 7-10 (Audra)

import jinja2
from flask import render_template, Blueprint
from pennchatsproject.models import TimeOption, Student


core = Blueprint('core', __name__)


# home page
@core.route('/')
def index():
    # more to come
    return render_template("index.html")


# about us page
@core.route('/info')
def info():
    return render_template('info.html')


@jinja2.contextfilter
@core.app_template_filter()
def query_time(context, time_id):
    time = TimeOption.query.get(time_id)
    return time.time_option


@jinja2.contextfilter
@core.app_template_filter()
def query_student_first_name(context, student_id):
    student = Student.query.get(student_id)
    return student.first_name


@jinja2.contextfilter
@core.app_template_filter()
def query_student_last_name(context, student_id):
    student = Student.query.get(student_id)
    return student.last_name


@jinja2.contextfilter
@core.app_template_filter()
def query_student_username(context, student_id):
    student = Student.query.get(student_id)
    return student.username


@jinja2.contextfilter
@core.app_template_filter()
def query_student_email(context, student_id):
    student = Student.query.get(student_id)
    return student.email

pennchatsproject/students/views.py
# pennchatsproject/students/views.py
# contains routing code for eight views
# register, login, logout, sign-up for next week's chat, thank you, account, edit profile, <username> profile page

from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from pennchatsproject import db
from pennchatsproject.models import *
from pennchatsproject.students.forms import *


students = Blueprint('students', __name__)


# register
@students.route('/register', methods=["POST", "GET"])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        student = Student(email=form.email.data,
                          username=form.username.data,
                          student_id=form.student_id.data
                          )
        student.set_password(form.password.data)
        db.session.add(student)
        db.session.commit()
        flash('Thank you for registering!')
        return redirect(url_for('students.login'))

    return render_template("register.html", form=form)


# login
@students.route('/login', methods=["POST", "GET"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        # Grab the student from our Student Models table
        student = Student.query.filter_by(email=form.email.data).first()

        if student.check_password(form.password.data) and student is not None:
            # log in the user by calling in the login_user method
            login_user(student)
            # flash a msg with the following message
            flash('You have logged in successfully!')
            # if a user was trying to visit a page that requires a log, flask saves that URL as 'next'
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)

    return render_template("login.html", form=form)


# logout
@students.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have successfully logged out.")
    return redirect(url_for('core.index'))


# update profile page
@students.route('/edit_profile', methods=["POST", "GET"])
@login_required
def edit_profile():
    form = ProfileForm()

    if form.validate_on_submit():

        current_user.username = form.username.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.city = form.city.data
        current_user.state = form.state.data
        current_user.country = form.country.data
        current_user.linkedin = form.linkedin.data
        current_user.bio = form.bio.data
        current_user.current_courses = form.current_courses.data
        current_user.past_courses = form.past_courses.data
        current_user.course_id_to_match = form.course_id_to_match.data
        current_user.interests = form.interests.data
        current_user.interest_id_to_match = form.interest_id_to_match.data
        current_user.cohort = form.cohort.data

        db.session.commit()
        flash('Profile Updated')
        return redirect(url_for('students.student_profile', username=current_user.username))

    elif request.method == 'GET':

        form.username.data = current_user.username
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.city.data = current_user.city
        form.state.data = current_user.state
        form.country.data = current_user.country
        form.linkedin.data = current_user.linkedin
        form.bio.data = current_user.bio
        form.current_courses.data = current_user.current_courses
        form.past_courses.data = current_user.past_courses
        form.course_id_to_match.data = current_user.course_id_to_match
        form.interests.data = current_user.interests
        form.interest_id_to_match.data = current_user.interest_id_to_match
        form.cohort.data = current_user.cohort

    return render_template('edit_profile.html', form=form)


# sign up-for next week's chat
@students.route('/sign_up', methods=["POST", "GET"])
@login_required
def sign_up():
    form = WeeklySignUpForm()

    if form.validate_on_submit():

        all_signups = WeeklySignUp.query.all()
        num_of_signups = len(all_signups)

        form = WeeklySignUp(signup_id=1+num_of_signups,
                            meeting_week_name=form.week_meet.data,
                            student_id=current_user.student_id,
                            prime_time_id=form.prime_time_id.data,
                            sec_time_id=form.sec_time_id.data,
                            prime_networking_goal_id=form.prime_networking_goal_id.data,
                            sec_networking_goal_id=form.sec_networking_goal_id.data
                            )

        db.session.add(form)
        db.session.commit()
        flash('Signup Form Submitted')
        return redirect(url_for('students.thank_you'))

    return render_template("weekly_signup.html", form=form)


# thank you
@students.route('/thank_you')
def thank_you():
    return render_template('thank_you.html')


# my meetings
@students.route('/my_meetings')
@login_required
def my_meetings():
    student_id = current_user.student_id
    meetings = []
    all_meetings = Meeting.query.all()
    for meeting in all_meetings:
        for student in meeting.students:
            if student_id == student.student_id:
                meetings.append(meeting)

    return render_template("my_meetings.html", meetings=meetings)


# <username> profile page
@students.route("/<username>")
def student_profile(username):
    student = Student.query.filter_by(username=username).first_or_404()
    return render_template("student_profile.html", student=student,
                           interests=student.interests,
                           current_courses=student.current_courses,
                           past_courses=student.past_courses)

pennchatsproject/templates/_formhelpers.html
<!-- https://flask.palletsprojects.com/en/2.0.x/patterns/wtforms/ -->

{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  </dd>
{% endmacro %}

pennchatsproject/templates/base.html
{# includes html code for the original bootstrap links, nav bar code, container block #}
{# Audra to copy her base.html from her templates folder #}

<!-- Jinja template for all html files -->

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock %} | Penn Chats</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- favicon -->
    <link rel="shortcut icon" type="image/jpg" href="https://user-images.githubusercontent.com/84137452/124787872-da51ca80-df16-11eb-8ab6-954a5e3d1bee.png"/>
  </head>


  <body>

  <div class="container"><h2>{% block head %} {% endblock %}</h2></div>

<!-- Bootstrap CDN navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <a class="navbar-brand">
            <img alt="Penn Chats logo"
                 src="https://user-images.githubusercontent.com/84137452/124787872-da51ca80-df16-11eb-8ab6-954a5e3d1bee.png"
                 style="max-width:40px">
        </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('core.index') }}">Penn Chats</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="{{ url_for('core.info') }}">About Us</a></li>
          {% if current_user.is_authenticated %}
            <li><a href="{{url_for('students.edit_profile')}}">Edit Profile</a></li>
            <li><a href="{{url_for('students.sign_up')}}">Sign Up for PennChats</a></li>
            <li><a href="{{url_for('students.my_meetings')}}">My Meetings</a></li>
            <li><a href="{{url_for('students.logout')}}">Logout</a></li>
          {% else %}
            <li><a href="{{url_for('students.login')}}">Login</a></li>
            <li><a href="{{url_for('students.register')}}">Register</a></li>
          {% endif %}
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

      <div class="container">
          {% block content %} {% endblock %}
      </div>
  </body>
</html>

pennchatsproject/templates/edit_profile.html
{% extends "base.html" %}

{% block title %} Edit Profile {% endblock %}

{% block content %}

<!-- import form template -->
{% from "_formhelpers.html" import render_field %}
<div class="jumbotron">
    <div class="container">
        <h2>Profile for {{current_user.username}}</h2>
        <form class="form form-horizontal" action="{{url_for('students.edit_profile')}}" method="POST" role="form">
            {{ form.hidden_tag() }}
            <!-- Name row -->
            <div class="row">
                <div class="col-sm-3">
                    <!-- Username Field -->
                    {{ render_field(form.username) }}
                </div>
                <div class="col-sm-3">
                    <!-- First Name Field -->
                    {{ render_field(form.first_name) }}
                </div>
                <div class="col-sm-3">
                    <!-- Last Name Field -->
                    {{ render_field(form.last_name) }}<br>
                </div>
            </div>

            <!-- City, state, country row -->
            <div class="row">
                <div class="col-sm-3">
                    <!-- City Field -->
                    {{ render_field(form.city) }}
                </div>
                <div class="col-sm-3">
                    <!-- State Field -->
                    {{ render_field(form.state) }}<br>
                </div>
                <div class="col-sm-3">
                    <!-- Country Field -->
                    {{ render_field(form.country) }}<br>
                </div>
            </div>

            <!-- Primary Class Field -->
            {{ render_field(form.course_id_to_match) }}<br>

            <!-- Courses row -->
            <div class="row">
                <div class="col-md-6">
                    <!-- Class Field -->
                    {{ render_field(form.past_courses) }}
                </div>
                <div class="col-md-6">
                    <!-- Current Class Field -->
                    {{ render_field(form.current_courses) }}
                </div>
            </div>
            <br>

            <!-- Primary Interest Field -->
            {{ render_field(form.interest_id_to_match) }}
            <br>

            <!-- Interests and cohort row -->
            <div class="row">
                <div class="col-md-6">
                    <!-- Interests Field -->
                    {{ render_field(form.interests) }}
                </div>
                <div class="col-md-6">
                    <!-- Cohort Field -->
                    {{ render_field(form.cohort) }}<br>
                </div>
            </div>

            <!-- LinkedIn Field -->
            {{ render_field(form.linkedin) }}
            <br>

            <!-- Bio Field -->
            {{ render_field(form.bio) }}
            <br>

            <!-- Submit Field -->
            {{ form.submit }}

        </div>
</form>


</div>
{% endblock %}

pennchatsproject/templates/generate_meeting.html
{% extends "base.html" %}

{% block title %} Generate Meetings {% endblock %}

{% block content %}

{% from "_formhelpers.html" import render_field %}

<div class="jumbotron">
    <h2>Generate Meetings</h2>
    <form method="POST" style="padding:5px;">
        <!-- Week Meet Field -->
        {{ form.hidden_tag() }}
        {{ render_field(form.week_meet) }}
        <br>

        <!-- Submit Field -->
        {{ form.submit() }}
    </form>
</div>

{% endblock %}

pennchatsproject/templates/generate_meetings.html
{% extends "base.html" %}

{% block title %} Generate Meetings {% endblock %}

{% block head %} Generate Meetings {% endblock %}

{% block content %}
<div style="text-align: center;">
  <div style="display: inline-block; text-align: left;">
    <form method="POST" style="padding:5px;">
        <!-- Email Field -->
        {{ form.hidden_tag() }}
        {{ form.week_meet.label }}:
        {{ form.week_meet }}
        <br>

        <!-- Submit Field -->
        {{ form.submit }}
    </form>
  </div>
</div>


{% endblock %}

pennchatsproject/templates/index.html
{# includes html code that renders the homepage (home.html) #}
{# Audra to copy her home.thml from her templates folder #}

{% extends "base.html" %}

{% block title %} Penn Chats {% endblock %}

{% block head %} {% endblock %}

{% block content%}

    <!--Homepage Image -->
    <img alt="Students having a conversation"
         class="img-responsive"
         src="https://user-images.githubusercontent.com/84137452/125167996-4fb8d780-e171-11eb-8ff6-5efd9d9cc9ff.jpg"
         style="float:left">

    <!-- Intro paragraph -->
    <div class="jumbotron">
      <br>
        <br>
      <!-- If student is signed in -->
      {% if current_user.is_authenticated %}
        <!-- Intro paragraph -->
        <h2 class="display-4">Welcome to Penn Chats, {{current_user.username}}!</h2>
        <p class="lead">Penn Chats is a platform designed to connect
        MCIT Online students. Tell us what classes you
        are taking, your interests, and when you'd like to meet,
        and we'll match you with a group of 2-5 students for a chat!</p>
        <p>Please ensure you have updated your profile before 
          signing up for PennChats.</p>
      <!-- If studnet is not signed in -->
      {% else %}
      <!-- Signup/Login buttons -->
      <center>
          <h1 class="display-4">Welcome to Penn Chats!</h1>
          <p class="lead">Penn Chats is a platform designed to connect
          MCIT Online students. Tell us what classes you
          are taking, your interests, and when you'd like to meet,
          and we'll match you with a group of 2-5 students for a chat!</p>
      </center>
      {% endif %}
     </div>


{% endblock %}

pennchatsproject/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}

{% from "_formhelpers.html" import render_field %}

<div class="jumbotron">
    <h2>Login</h2>
    <form method="POST" style="padding:5px;">
        <!-- Email Field -->
        {{ form.hidden_tag() }}
        {{ render_field(form.email) }}
        <br>

        <!-- Password Field -->
        {{ render_field(form.password) }}
        <br>

        <!-- Submit Field -->
        {{ form.submit() }}
    </form>
</div>


{% endblock %}

pennchatsproject/templates/logout.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Thank You</h1>
    <p>You have been successfully logged out. We hope to see you again soon!</p>
  </div>
{% endblock %}

pennchatsproject/templates/my_meetings.html
{% extends "base.html" %}

{% block title %} My Meetings {% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    
    <div style="text-align: center;">
      <div style="display: inline-block; text-align: left;">

        <h2>Matched Meetings for {{current_user.first_name}} {{current_user.last_name}}</h2>
        
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Meeting Week</th>
              <th scope="col">Meeting Time</th>
              <th scope="col">Participants</th>
            </tr>
          </thead>
          <tbody>
            {% for meeting in meetings %}
              <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ meeting.meeting_week_name }}</td>
                <td>{{ meeting.time_id | query_time }}</td>
                <td>
                  {% for student in meeting.students %}
                    <a href="{{url_for('students.student_profile', username=student.username)}}">{{ student.first_name }} {{ student.last_name }} | </a>
                  {% endfor %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        
      </div>
    </div>
  </div>

</div>

{% endblock %}

pennchatsproject/templates/register.html
{% extends "base.html" %}

{% block title %} Register {% endblock %}

{% block content %}

{% from "_formhelpers.html" import render_field %}

<div class="jumbotron">
    <h2>Register</h2>
    <form method="POST" style="padding:5px;">
        {{ form.hidden_tag() }}
        <!-- Email Field -->
        {{ render_field(form.email) }}
        <br>

        <!-- Username Field -->
        {{ render_field(form.username) }}
        <br>

        <!-- Student_id Field -->
        {{ render_field(form.student_id) }}
        <br>

        <!-- Password Field -->
        {{ render_field(form.password) }}
        <br>

        <!-- Confirm Password Field -->
        {{ render_field(form.pass_confirm) }}
        <br>

        <!-- Submit Field -->
        {{ form.submit }}
    </form>
</div>


{% endblock %}

pennchatsproject/templates/results.html
{% extends "base.html" %}

{% block title %} Results {% endblock %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <div style="text-align: center;">
      <div style="display: inline-block; text-align: left;">
        

        <h2>Matched Meetings</h2>
        
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Meeting Week</th>
              <th scope="col">Meeting Time</th>
              <th scope="col">Participants</th>
            </tr>
          </thead>
          <tbody>
            {# {% for meeting in meetings %}  #}
            {% for meeting in meetings %}
              <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ meeting.meeting_week_name }}</td>
                <td>{{ meeting.time_id | query_time }}</td>
                <td>
                  {% for student in meeting.students %}
                    <a href="{{url_for('students.student_profile', username=student.username)}}">{{ student.first_name }} {{ student.last_name }} | </a>
                  {% endfor %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        
        <h2>Unmatched Students</h2>
        
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Meeting Week</th>
              <th scope="col">Student</th>
              <th scope="col">Email</th>
            </tr>
          </thead>
          <tbody>
            {% for student in unmatched_students %} 
              <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ student.meeting_week_name }}</td>
                <td><a href="{{url_for('students.student_profile', username=student.student_id|query_student_username)}}">{{ student.student_id | query_student_first_name }} {{ student.student_id | query_student_last_name }}</a></td>
                <td><a href="mailto:{{student.student_id|query_student_email}}">{{student.student_id|query_student_email}}</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>


      </div>
    </div>
  </div>
</div>

{% endblock %}

pennchatsproject/templates/student_profile.html
{% extends "base.html" %}

{% block title %} Profile of {{ student.first_name }} {{ student.last_name }} {% endblock %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <div align='center'>
      <h2>{{ student.first_name }} {{ student.last_name }}</h2>
      <p>{{ student.city }} {{ student.state }} {{ student.country }}</p>
      <p>Interests: {% for interest in interests %} {{interest.interest_name}} |{% endfor %}</p>
      MCIT Online Cohort: {{ student.cohort }} 
      <br>
      LinkedIn: <a href="{{ student.linkedin }}">{{student.linkedin}}</a> 
      <br>
      Email: <a href="mailto:{{student.email}}">{{student.email}}</a>
      <br>
      {% if student.bio %} Bio: {{ student.bio }} {% endif %}
      
      <h3>Current Courses</h3>
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Course ID</th>
            <th scope="col">Course Name</th>
          </tr>
        </thead>
        <tbody>
          {% for course in current_courses %} 
            <tr>
              <th scope="row">{{ loop.index }}</th>
              <td>{{ course.course_id }}</td>
              <td>{{ course.course_name }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <br>
      
      <h3>Past Courses</h3>
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Course ID</th>
            <th scope="col">Course Name</th>
          </tr>
        </thead>
        <tbody>
          {% for course in past_courses %} 
            <tr>
              <th scope="row">{{ loop.index }}</th>
              <td>{{ course.course_id }}</td>
              <td>{{ course.course_name }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <br>
    </div>
  </div>
</div>

{% endblock %}

pennchatsproject/templates/thank_you.html
{% extends "base.html" %}

{% block title %} Thank You {% endblock %}

{% block content %}

<div class="jumbotron">
  <h2><div>Thank you for signing up for PennChats, {{current_user.first_name}}!</div></h2> 
  <h2><div>Your preferences have been submitted.</div></h2>
</div>
{% endblock %}

pennchatsproject/templates/weekly_signup.html
{% extends "base.html" %}

{% block title %} Sign Up for PennChats {% endblock %}

{% block content %}

{% from "_formhelpers.html" import render_field %}

<div class="jumbotron">
    <h2>Sign Up for PennChats</h2>
    <form method="POST" style="padding:5px;">
        {{ form.hidden_tag() }}
        <!-- Week Meet Field -->
        {{ render_field(form.week_meet) }}
        <br>

        <!-- Prime Time Field -->
        {{ render_field(form.prime_time_id) }}
        <br>

        <!-- Sec Time Field -->
        {{ render_field(form.sec_time_id) }}
        <br>

        <!-- Prime Networking Goal Field -->
        {{ render_field(form.prime_networking_goal_id) }}
        <br>

        <!-- Sec Networking Goal Field -->
        {{ render_field(form.sec_networking_goal_id) }}
        <br>

        <!-- Submit Field -->
        {{ form.submit }}
    </form>
</div>

{% endblock %}